In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9732, 5678, 9674, 3454],
 [9732, 5678, 9674, 7594],
 [9732, 822, 9674, 3050],
 [1522, 3648, 5082, 6087, 1232],
 [1522, 3648, 5082, 6087, 7385],
 [156, 9732, 5664, 9674, 90],
 [8121, 4480, 8441, 6087]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9732 5678 9674 3454]
 [   0    0    0    0 9732 5678 9674 7594]
 [   0    0    0    0 9732  822 9674 3050]
 [   0    0    0 1522 3648 5082 6087 1232]
 [   0    0    0 1522 3648 5082 6087 7385]
 [   0    0    0  156 9732 5664 9674   90]
 [   0    0    0    0 8121 4480 8441 6087]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Udemy Course\SimpleRNN\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step


array([[[ 0.00310757, -0.03304541, -0.03465011, -0.01587422,
          0.00208833, -0.01564886,  0.04265448, -0.03400549,
          0.02594128,  0.02669526],
        [ 0.00310757, -0.03304541, -0.03465011, -0.01587422,
          0.00208833, -0.01564886,  0.04265448, -0.03400549,
          0.02594128,  0.02669526],
        [ 0.00310757, -0.03304541, -0.03465011, -0.01587422,
          0.00208833, -0.01564886,  0.04265448, -0.03400549,
          0.02594128,  0.02669526],
        [ 0.00310757, -0.03304541, -0.03465011, -0.01587422,
          0.00208833, -0.01564886,  0.04265448, -0.03400549,
          0.02594128,  0.02669526],
        [ 0.0026843 ,  0.02500493, -0.04751918,  0.01625582,
          0.02728988,  0.02411186, -0.01187963, -0.029744  ,
          0.04767933,  0.04265497],
        [ 0.00650555,  0.02546742,  0.03282075, -0.04710311,
          0.04792322,  0.04531242, -0.02410144, -0.03164677,
          0.03733814,  0.00868506],
        [-0.03323472, -0.04305045,  0.0399174 ,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 9732, 5678, 9674, 3454], dtype=int32)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step


array([[[ 0.00310757, -0.03304541, -0.03465011, -0.01587422,
          0.00208833, -0.01564886,  0.04265448, -0.03400549,
          0.02594128,  0.02669526],
        [ 0.00310757, -0.03304541, -0.03465011, -0.01587422,
          0.00208833, -0.01564886,  0.04265448, -0.03400549,
          0.02594128,  0.02669526],
        [ 0.00310757, -0.03304541, -0.03465011, -0.01587422,
          0.00208833, -0.01564886,  0.04265448, -0.03400549,
          0.02594128,  0.02669526],
        [ 0.00310757, -0.03304541, -0.03465011, -0.01587422,
          0.00208833, -0.01564886,  0.04265448, -0.03400549,
          0.02594128,  0.02669526],
        [ 0.0026843 ,  0.02500493, -0.04751918,  0.01625582,
          0.02728988,  0.02411186, -0.01187963, -0.029744  ,
          0.04767933,  0.04265497],
        [ 0.00650555,  0.02546742,  0.03282075, -0.04710311,
          0.04792322,  0.04531242, -0.02410144, -0.03164677,
          0.03733814,  0.00868506],
        [-0.03323472, -0.04305045,  0.0399174 ,  0.0